---
language: shell
env:
  - IMAGE_NAME="nansencenter/geospaas:latest"
services: docker
script:

  - docker run --rm -v "$(pwd):/src" $IMAGE_NAME python setup.py sdist bdist_wheel
  - >
    docker run --rm
    -e "TRAVIS=true"
    -e TRAVIS_JOB_ID
    -e TRAVIS_BRANCH
    -e TRAVIS_PULL_REQUEST
    -v "$(pwd):/src"
    $IMAGE_NAME
    bash -c "source /opt/conda/bin/activate
    && coverage run --source=./geospaas_adas_viewer runtests.py && coveralls"
# If the build is triggered by a tag and an API token is defined for the branch
# (in the travis repository settings), a package is built and added to the release
#
deploy:
  on:
    tags: true
    condition: -n "${GITHUB_API_TOKEN}"
  provider: releases
  api_key: "${GITHUB_API_TOKEN}"
  file: 'dist/*'
  file_glob: true
  skip_cleanup: true
...
